default_platform(:ios)

platform :ios do
  desc 'Publish app to the iTunes Connect'
  lane :publish do
    app_store_connect_api_key(
      key_id: env('API_KEY_ID'),
      issuer_id: env('API_KEY_ISSUER'),
      key_filepath: env('API_KEY_FILE_PATH', nil_if_empty: true)
      key_content: env('API_KEY_CONTENT', nil_if_empty: true)
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )


  end

  def env(key, nil_if_empty: false, as_boolean: false)
    value = ENV[key]
    return value if value.nil?
    return nil if nil_if_empty && value.empty?
    if as_boolean
      return false if value.nil? || value == false || value.empty? || value =~ (/(false|f|no|n|0)$/i)
      return true if value == true || value =~ (/(true|t|yes|y|1)$/i)
    end
    value
  end
end
